namespace Unheft.Tests;

public static class TestFixtures
{
    public const string DesignerFile = @"// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnheftDemo.Data;

#nullable disable

namespace UnheftDemo.Data.Migrations
{
    [DbContext(typeof(UnheftDemoDbContext))]
    [Migration(""20251215053906_MgRemoveCustomerEmailJourney"")]
    partial class MgRemoveCustomerEmailJourney
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation(""ProductVersion"", ""9.0.0"")
                .HasAnnotation(""Relational:MaxIdentifierLength"", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity(""UnheftDemo.Data.Customer"", b =>
            {
                b.Property<int>(""Id"")
                    .ValueGeneratedOnAdd()
                    .HasColumnType(""int"");

                b.HasKey(""Id"");

                b.ToTable(""Customers"");
            });
#pragma warning restore 612, 618
        }
    }
}
";

    public const string MainMigrationFile = @"using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UnheftDemo.Data.Migrations
{
    /// <inheritdoc />
    public partial class MgRemoveCustomerEmailJourney : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: ""EmailJourney"",
                table: ""Customers"");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: ""EmailJourney"",
                table: ""Customers"",
                type: ""nvarchar(max)"",
                nullable: true);
        }
    }
}
";

    public const string AlreadyConsolidatedFile = @"using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UnheftDemo.Data;

#nullable disable

namespace UnheftDemo.Data.Migrations
{
    [DbContext(typeof(UnheftDemoDbContext))]
    [Migration(""20251215053906_MgRemoveCustomerEmailJourney"")]
    /// <inheritdoc />
    public partial class MgRemoveCustomerEmailJourney : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }

        /// <summary>
        /// Intentionally empty. The original Designer file has been archived by unheft.
        /// </summary>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
";

    public const string DesignerFileNoAttributes = @"// <auto-generated />
using System;

namespace UnheftDemo.Data.Migrations
{
    partial class SomeClass
    {
        protected override void BuildTargetModel(object modelBuilder)
        {
        }
    }
}
";

    /// <summary>
    /// Creates a temporary directory with a migration pair for testing.
    /// </summary>
    public static string CreateMigrationPairOnDisk(string? tempDir = null)
    {
        tempDir ??= Path.Combine(Path.GetTempPath(), "unheft-test-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempDir);

        var mainPath = Path.Combine(tempDir, "20251215053906_MgRemoveCustomerEmailJourney.cs");
        var designerPath = Path.Combine(tempDir, "20251215053906_MgRemoveCustomerEmailJourney.Designer.cs");

        File.WriteAllText(mainPath, MainMigrationFile);
        File.WriteAllText(designerPath, DesignerFile);

        return tempDir;
    }

    /// <summary>
    /// Creates multiple migration pairs for testing.
    /// </summary>
    public static string CreateMultipleMigrationPairsOnDisk()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), "unheft-test-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempDir);

        // Pair 1
        File.WriteAllText(
            Path.Combine(tempDir, "20251215053906_MgRemoveCustomerEmailJourney.cs"),
            MainMigrationFile);
        File.WriteAllText(
            Path.Combine(tempDir, "20251215053906_MgRemoveCustomerEmailJourney.Designer.cs"),
            DesignerFile);

        // Pair 2 - similar structure
        var main2 = MainMigrationFile
            .Replace("MgRemoveCustomerEmailJourney", "MgAddOrderTable")
            .Replace("EmailJourney", "OrderId");
        var designer2 = DesignerFile
            .Replace("MgRemoveCustomerEmailJourney", "MgAddOrderTable")
            .Replace("20251215053906", "20251216120000");

        File.WriteAllText(
            Path.Combine(tempDir, "20251216120000_MgAddOrderTable.cs"),
            main2);
        File.WriteAllText(
            Path.Combine(tempDir, "20251216120000_MgAddOrderTable.Designer.cs"),
            designer2);

        return tempDir;
    }
}
